name: Ejecutar script Python

on:
  schedule:
    # GitHub Actions permite mÃ­nimo cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    # ðŸ”¥ MUY IMPORTANTE:
    # Indica que este job usa el Environment donde estÃ¡ el secret
    environment: GOOGLE_DRIVE_JSON

    steps:
      # Clonar el repositorio
      - uses: actions/checkout@v3

      # Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt python-dotenv openpyxl pandas google-api-python-client

      # Ejecutar script
      - name: Run script
        run: python main.py
        env:
          GOOGLE_DRIVE_JSON: ${{ secrets.GOOGLE_DRIVE_JSON }}
